// Fonte ÚNICA das tabelas de WhatsApp (wa_*) e Financeiro (fin_*).
//
// Antes, estes CREATE TABLE estavam copiados IDÊNTICOS em dois caminhos de
// runtime: no endpoint POST /admin/setup e no ensureSchema() do boot. Qualquer
// coluna nova precisava ser adicionada nos dois — fonte clássica de divergência.
// Agora ficam aqui e os dois lugares importam esta lista.
//
// Observações de segurança da mudança:
//  - São CREATE TABLE IF NOT EXISTS: em bancos que já existem (produção) são
//    no-op, então unificar não altera nada do que já está no ar.
//  - Os CREATE INDEX não têm IF NOT EXISTS (MySQL não suporta); se o índice já
//    existe, o erro é capturado pelo try/catch de cada call site — idempotente.
//  - As migrações ALTER/seed continuam em cada call site (não são tocadas aqui).
export const WA_FIN_DDL: string[] = [
  "CREATE TABLE IF NOT EXISTS `wa_contacts` (`id` int AUTO_INCREMENT NOT NULL, `waNumber` varchar(32) NOT NULL, `jid` varchar(128), `lid` varchar(128), `clientId` int, `name` varchar(255), `avatarUrl` mediumtext, `createdAt` timestamp NOT NULL DEFAULT (now()), `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `wa_contacts_id` PRIMARY KEY(`id`), CONSTRAINT `wa_contacts_waNumber_unique` UNIQUE(`waNumber`))",
  "CREATE TABLE IF NOT EXISTS `wa_conversations` (`id` int AUTO_INCREMENT NOT NULL, `contactId` int NOT NULL, `status` enum('queue','active','concluded','dismissed') NOT NULL DEFAULT 'queue', `assignedAgentId` int, `unreadCount` int NOT NULL DEFAULT 0, `lastMessageAt` timestamp NOT NULL DEFAULT (now()), `concludedAt` timestamp NULL, `queuedAt` timestamp NULL, `assignedAt` timestamp NULL, `lastAutoReplyAt` timestamp NULL, `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `wa_conversations_id` PRIMARY KEY(`id`))",
  "CREATE TABLE IF NOT EXISTS `wa_messages` (`id` int AUTO_INCREMENT NOT NULL, `conversationId` int NOT NULL, `senderType` enum('contact','agent','system') NOT NULL, `fromMe` boolean NOT NULL DEFAULT false, `content` text, `messageType` enum('text','image','audio','video','document','sticker','location','template','other') NOT NULL DEFAULT 'text', `mediaUrl` mediumtext, `replyTo` text, `waMessageId` varchar(128), `status` enum('received','sent','delivered','read','failed') NOT NULL DEFAULT 'sent', `agentId` int, `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `wa_messages_id` PRIMARY KEY(`id`))",
  "CREATE TABLE IF NOT EXISTS `wa_tags` (`id` int AUTO_INCREMENT NOT NULL, `name` varchar(64) NOT NULL, `color` varchar(20) NOT NULL DEFAULT '#3E9AA6', CONSTRAINT `wa_tags_id` PRIMARY KEY(`id`), CONSTRAINT `wa_tags_name_unique` UNIQUE(`name`))",
  "CREATE TABLE IF NOT EXISTS `wa_conversation_tags` (`id` int AUTO_INCREMENT NOT NULL, `conversationId` int NOT NULL, `tagId` int NOT NULL, CONSTRAINT `wa_conversation_tags_id` PRIMARY KEY(`id`))",
  "CREATE TABLE IF NOT EXISTS `wa_sessions` (`id` int AUTO_INCREMENT NOT NULL, `sessionName` varchar(64) NOT NULL, `keyId` varchar(255) NOT NULL, `keyData` mediumtext, `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `wa_sessions_id` PRIMARY KEY(`id`), CONSTRAINT `wa_sessions_name_key_unique` UNIQUE(`sessionName`,`keyId`))",
  "CREATE TABLE IF NOT EXISTS `wa_config` (`k` varchar(64) NOT NULL, `v` text, CONSTRAINT `wa_config_k` PRIMARY KEY(`k`))",
  "CREATE TABLE IF NOT EXISTS `wa_push_subs` (`id` int AUTO_INCREMENT NOT NULL, `endpoint` varchar(512) NOT NULL, `p256dh` varchar(255), `auth` varchar(255), `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `wa_push_subs_id` PRIMARY KEY(`id`), CONSTRAINT `wa_push_subs_endpoint_unique` UNIQUE(`endpoint`))",
  "CREATE TABLE IF NOT EXISTS `wa_scheduled_messages` (`id` int AUTO_INCREMENT NOT NULL, `conversationId` int NOT NULL, `agentId` int NOT NULL, `content` text NOT NULL, `sendAt` timestamp NOT NULL, `status` enum('pending','sent','failed','cancelled') NOT NULL DEFAULT 'pending', `errorMsg` text, `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `wa_scheduled_messages_id` PRIMARY KEY(`id`))",
  "CREATE TABLE IF NOT EXISTS `fin_client_config` (`id` int AUTO_INCREMENT NOT NULL, `clientId` int NOT NULL, `hasHonorario` boolean NOT NULL DEFAULT false, `honorarioValue` varchar(20), `dueDay` int, `sendDay` int, `weekendRule` enum('mantem','antecipa','posterga') NOT NULL DEFAULT 'mantem', `billingEmail` varchar(320), `recurring` boolean NOT NULL DEFAULT true, `activated` boolean NOT NULL DEFAULT false, `lastGenComp` varchar(7), `active` boolean NOT NULL DEFAULT true, `createdAt` timestamp NOT NULL DEFAULT (now()), `updatedAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `fin_client_config_id` PRIMARY KEY(`id`), CONSTRAINT `fin_client_config_clientId_unique` UNIQUE(`clientId`))",
  "CREATE TABLE IF NOT EXISTS `fin_titulos` (`id` int AUTO_INCREMENT NOT NULL, `clientId` int NOT NULL, `kind` enum('honorario','eventual') NOT NULL DEFAULT 'eventual', `description` varchar(255) NOT NULL, `category` varchar(80), `amount` varchar(20) NOT NULL, `competencia` varchar(7), `dueDate` timestamp NOT NULL, `sendDate` timestamp NULL, `status` enum('rascunho','aberto','enviado','em_conferencia','pago','vencido','cancelado') NOT NULL DEFAULT 'aberto', `origin` enum('manual','recorrencia','tarefa') NOT NULL DEFAULT 'manual', `recurringConfigId` int, `taskId` int, `sentAt` timestamp NULL, `reminderSentAt` timestamp NULL, `createdAt` timestamp NOT NULL DEFAULT (now()), `updatedAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `fin_titulos_id` PRIMARY KEY(`id`))",
  "CREATE TABLE IF NOT EXISTS `fin_payments` (`id` int AUTO_INCREMENT NOT NULL, `tituloId` int NOT NULL, `comprovanteUrl` mediumtext, `amount` varchar(20), `paidDate` timestamp NULL, `method` varchar(30), `status` enum('aguardando_conferencia','confirmado','rejeitado') NOT NULL DEFAULT 'aguardando_conferencia', `submittedByClient` boolean NOT NULL DEFAULT false, `confirmedBy` int, `confirmedAt` timestamp NULL, `note` varchar(500), `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `fin_payments_id` PRIMARY KEY(`id`))",
  "CREATE TABLE IF NOT EXISTS `fin_config` (`id` int AUTO_INCREMENT NOT NULL, `pixKey` varchar(200), `pixKeyType` varchar(20), `beneficiaryName` varchar(200), `beneficiaryDoc` varchar(20), `pixQrImage` mediumtext, `instructions` text, `active` boolean NOT NULL DEFAULT false, `autoCobranca` boolean NOT NULL DEFAULT false, `lembreteDias` int NOT NULL DEFAULT 2, `updatedAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `fin_config_id` PRIMARY KEY(`id`))",
  "CREATE TABLE IF NOT EXISTS `fin_payables` (`id` int AUTO_INCREMENT NOT NULL, `description` varchar(255) NOT NULL, `supplier` varchar(200), `category` varchar(80), `amount` varchar(20) NOT NULL, `dueDate` timestamp NOT NULL, `status` enum('aberto','pago','vencido','cancelado') NOT NULL DEFAULT 'aberto', `recurring` boolean NOT NULL DEFAULT false, `paidDate` timestamp NULL, `paidBy` int, `note` varchar(500), `createdAt` timestamp NOT NULL DEFAULT (now()), `updatedAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `fin_payables_id` PRIMARY KEY(`id`))",
  "CREATE INDEX `wa_messages_conv_idx` ON `wa_messages` (`conversationId`, `createdAt`)",
  "CREATE INDEX `wa_conversations_status_idx` ON `wa_conversations` (`status`, `lastMessageAt`)",
];
